_urlopen: partly revert earlier change
In 4b57307865cf4bcde8ef5150303eb48465a43689, I also made a speculative
fix to timestamp_to_http but that turns out to be wrong (though I thought
I'd tested that too):
```
$ emerge -G hello -v --jobs=1
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.13/emerge", line 57, in main
    retval = emerge_main()
  File "/usr/lib/python3.13/site-packages/_emerge/main.py", line 1314, in emerge_main
    return run_action(emerge_config)
  File "/usr/lib/python3.13/site-packages/_emerge/actions.py", line 3521, in run_action
    mytrees["bintree"].populate(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        getbinpkgs="--getbinpkg" in emerge_config.opts,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/portage/dbapi/bintree.py", line 964, in populate
    self._populate_remote(
    ~~~~~~~~~~~~~~~~~~~~~^
        getbinpkg_refresh=getbinpkg_refresh,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        pretend=pretend,
        ^^^^^^^^^^^^^^^^
        verbose=verbose,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/portage/dbapi/bintree.py", line 1463, in _populate_remote
    f = _urlopen(
        url,
        if_modified_since=local_timestamp,
        proxies=proxies,
    )
  File "/usr/lib/python3.13/site-packages/portage/util/_urlopen.py", line 50, in urlopen
    request.add_header("If-Modified-Since", timestamp_to_http(if_modified_since))
                                            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/portage/util/_urlopen.py", line 70, in timestamp_to_http
    stamp = mktime_tz(dt.timetuple())
  File "/usr/lib/python3.13/email/_parseaddr.py", line 193, in mktime_tz
    if data[9] is None:
       ~~~~^^^
IndexError: tuple index out of range
```

Revert that part. I think it's unnecessary anyway because of the formatdate
call.

Bug: https://bugs.gentoo.org/962832
Fixes: 4b57307865cf4bcde8ef5150303eb48465a43689
Signed-off-by: Sam James <sam@gentoo.org>