IndexError: tuple index out of range
I got confused with on-disk format, and the array that is used here.



svn path=/main/branches/prefix/; revision=10727