The python that's inside stage 1 or 2 is built with a minimal configuration which does not include the /usr/lib/pythonX.Y/encodings directory. This results in error like the following:
  LookupError: no codec search functions registered: can't find encoding

In order to solve this problem, detect it early and manually register
a search function for the ascii codec. Starting with python-3.0 this
problem is more noticeable because of stricter handling of encoding
and decoding between strings of characters and bytes.

svn path=/main/trunk/; revision=12684