Prune circular nested sets from the digraph.
This prevents the following traceback which was reported in forum
thread 847007:

  File "pym/_emerge/depgraph.py", line 3694, in _merge_order_bias
    mygraph.order.sort(key=cmp_sort_key(cmp_merge_preference))
  File "pym/portage/util/__init__.py", line 808, in __lt__
    return self._cmp_func(self._obj, other._obj) < 0
  File "pym/_emerge/depgraph.py", line 3675, in cmp_merge_preference
    if node1.operation == 'uninstall':
AttributeError: 'SetArg' object has no attribute 'operation'