fix crash when using binhost due to using conditionally defined variable
extra_info didn't always exist, so if you get http 304 but no
Last-Modified, portage errors out with:

```
  File "/usr/lib/python3.13/site-packages/portage/dbapi/bintree.py", line 1519, in _populate_remote
    "up-to-date", extra_info
                  ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'extra_info' where it is not associated with a value
```

Fixes: c83466a50efdee2cac81a5ed6a660c11b9ac746e
Signed-off-by: Eli Schwartz <eschwartz@gentoo.org>