bintree: Fix UnboundLocalError due to extra_info
If the package index fetch results in a 304 without Last-Modified
header, then an UnboundLocalError will the thrown:

  File "/usr/lib/python3.13/site-packages/portage/dbapi/bintree.py", line 1519, in _populate_remote
    "up-to-date", extra_info
                  ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'extra_info' where it is not associated with a value

Fixes: c83466a50efd ("bintree: Improve UseCachedCopyOfRemoteIndex handling, report if TTL")
Signed-off-by: Florian Schmaus <flow@gentoo.org>