Use spawn instead of forkserver
This avoids forkserver errors of the form:

OSError: AF_UNIX path too long

Bug: https://bugs.gentoo.org/941956
Signed-off-by: Zac Medico <zmedico@gentoo.org>