portage/dispatch_conf.py: Fix bug 512690
This bug happened when a /etc/portage/package.* file was changed into a directory.
  File "/usr/lib64/portage/pym/portage/dispatch_conf.py", line 210, in file_archive_post_process
    os.rename(archive + '.dist.new', archive + '.dist')
NotADirectoryError: [Errno 20] Not a directory: '/etc/config-archive/etc/portage/package.unmask/unmask.dist'