_drop_privs_userfetch: ensure cwd is accessible
The cwd needs to be accessible in order for the multiprocessing
spawn start method to succeed:

  File "/usr/lib/python3.14/multiprocessing/spawn.py", line 235, in prepare
    os.chdir(data['dir'])
    ~~~~~~~~^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/root'

Bug: https://bugs.gentoo.org/965138
Signed-off-by: Zac Medico <zmedico@gentoo.org>