Revert "PORTAGE_NICENESS: Consider autogroup scheduling"
This reverts commit a4d882964ee1931462f911d0c46a80e27e59fa48.
It triggered this regression:

# PORTAGE_NICENESS=20 emerge -av --depclean
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/emerge", line 51, in <module>
    retval = emerge_main()
  File "/usr/lib/python3.9/site-packages/_emerge/main.py", line 1319, in emerge_main
    return run_action(emerge_config)
  File "/usr/lib/python3.9/site-packages/_emerge/actions.py", line 2999, in run_action
    apply_priorities(emerge_config.target_config.settings)
  File "/usr/lib/python3.9/site-packages/_emerge/actions.py", line 2635, in apply_priorities
    nice(settings)
  File "/usr/lib/python3.9/site-packages/_emerge/actions.py", line 2672, in nice
    out.eerror("%s\n" % str(e))
OSError: [Errno 22] Invalid argument

Bug: https://bugs.gentoo.org/777492#c4
Signed-off-by: Zac Medico <zmedico@gentoo.org>