bin: lock-helper.py: move more code into __name__ main guard for Python 3.14
I was still seeing (flaky!) test failures after e5b7b8a3ac0a710272e174851673e5eb74250a69 with:
```
FAILED lib/portage/tests/locks/test_asynchronous_lock.py::AsynchronousLockTestCase::testAsynchronousLockWaitKill
FAILED lib/portage/tests/process/test_spawn_returnproc.py::SpawnReturnProcTestCase::testSpawnReturnProcTerminate
FAILED lib/portage/tests/locks/test_asynchronous_lock.py::AsynchronousLockTestCase::testAsynchronousLockWaitKillHardlink
FAILED lib/portage/tests/locks/test_lock_nonblock.py::LockNonblockTestCase::testLockNonblockHardlink - AssertionError: 1 != 0
```

Move more code into the guard in bin/lock-helper.py. It seems to help a bit
but not sure if that's completely cured it. In other bin/*, we mostly call
disable_legacy_globals in the guard, so this seems right on that end too.

Bug: https://bugs.gentoo.org/941956
Signed-off-by: Sam James <sam@gentoo.org>