Make the global "actions" variable a local inside parse_opts() since the name collision with the _emerge.actions module triggers this traceback with epydoc-3.0.1:
Traceback (most recent call last):                                                                                                                                                             
  File "/usr/bin/epydoc", line 13, in <module>                                                                                                                                                 
    cli()                                                                                                                                                                                      
  File "/usr/lib/python2.6/site-packages/epydoc/cli.py", line 965, in cli                                                                                                                      
    main(options, names)                                                                                                                                                                       
  File "/usr/lib/python2.6/site-packages/epydoc/cli.py", line 757, in main                                                                                                                     
    exclude_parse=exclude_parse)                                                                                                                                                               
  File "/usr/lib/python2.6/site-packages/epydoc/docbuilder.py", line 235, in build_doc_index                                                                                                   
    docindex = DocIndex(docs)                                                                                                                                                                  
  File "/usr/lib/python2.6/site-packages/epydoc/apidoc.py", line 1715, in __init__                                                                                                             
    raise ValueError("All APIdocs passed to DocIndexer "                                                                                                                                       
ValueError: All APIdocs passed to DocIndexer must already have canonical names.  


svn path=/main/trunk/; revision=13674