bin/ebuild: Fix to work with installed package
Fix the following AttributeError error:

# ebuild /var/db/pkg/sys-apps/portage-2.3.71/portage-2.3.71.ebuild clean pretend clean
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/ebuild", line 318, in <module>
    type_name=pkg_type)
  File "/usr/lib64/python3.6/site-packages/_emerge/Package.py", line 72, in __init__
    db = self.cpv._db
AttributeError: 'str' object has no attribute '_db'

Bug: https://bugs.gentoo.org/532674
Fixes: bfe7892202b8 ("_pkg_str: add _db attribute (bug 640318)")
Signed-off-by: Zac Medico <zmedico@gentoo.org>