unmerge: stringify Atom before str operations
Atom is no longer a str subclass, but _unmerge_display() still indexed
and concatenated candidate_catpkgs entries directly, which crashed with

    TypeError: 'Atom' object is not subscriptable

when the operator-prefix check ran (i.e. whenever the initial match
failed). Take str() up front like the loop above does, and use it for
the operator check, the ambiguous-name message, and the "Couldn't find"
message.

Bug: https://bugs.gentoo.org/980394
Fixes: 7e15fc7fa ("dep: Atom: remove str subtyping")
Signed-off-by: Matt Turner <mattst88@gentoo.org>