ChildWatcherTestCase: python3.8 compat
Since python3.8, the add_child_handler method must be called
while the event loop is running, in order to avoid this error:

  File "lib/portage/tests/util/futures/asyncio/test_child_watcher.py", line 41, in testChildWatcher
    watcher.add_child_handler(pids[0], callback, *args_tuple)
  File "/opt/python/3.8-dev/lib/python3.8/asyncio/unix_events.py", line 1286, in add_child_handler
    loop = events.get_running_loop()
RuntimeError: no running event loop

See: https://travis-ci.org/gentoo/portage/jobs/597907096
Signed-off-by: Zac Medico <zmedico@gentoo.org>